# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://qabarr.com'
baseurl: ''
title: 'Quin Abarr'
description: 'All About Quin'
permalink: pretty
logo: /assets/images/qa.png

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: Research
  url: /research/
- title: Curriculum Vitae
  url: /cv/
- title: Personal
  url: /personal/
- title: Crosswords
  url: /xwords/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Crosswords
    output: true
    #description: "Some puzzles I have made"
    #feature_text: |
    #  Welcome to my blog
    feature_image: /assets/images/erebus_and_terror_cropped.jpg

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
